import streamlit as st
import pandas as pd
import os
from dotenv import load_dotenv
import plotly.express as px

# โหลดค่าจาก .env อัตโนมัติ (รองรับทั้งรันบน Local และเครื่องอื่น)
# ตรวจสอบว่ามีไฟล์ .env ในโฟลเดอร์เดียวกัน หรือใน root directory
env_path_parent = os.path.join(os.path.dirname(__file__), '..', '.env')
env_path_current = os.path.join(os.path.dirname(__file__), '.env')

if os.path.exists(env_path_current):
    load_dotenv(dotenv_path=env_path_current)
elif os.path.exists(env_path_parent):
    load_dotenv(dotenv_path=env_path_parent)
else:
    load_dotenv()

# นำเข้า supabase แบบ optional (ไม่ crash ถ้าไม่ได้ติดตั้ง)
try:
    from supabase import create_client, Client
    SUPABASE_AVAILABLE = True
except ImportError:
    SUPABASE_AVAILABLE = False

st.set_page_config(page_title="ICT Trading Bot Dashboard", layout="wide", page_icon="📈")

@st.cache_resource
def init_connection():
    """เชื่อมต่อ Supabase ผ่าน os.getenv() เท่านั้น ไม่พึ่ง st.secrets"""
    if not SUPABASE_AVAILABLE:
        return None
    url = os.getenv("SUPABASE_URL")
    key = os.getenv("SUPABASE_KEY")
    if not url or not key:
        return None
    try:
        return create_client(url, key)
    except Exception:
        return None

supabase = init_connection()

st.title("📈 ICT & SMC Algorithmic Trading Dashboard")
st.markdown("ระบบเทรดอัตโนมัติตามหลักการ Inner Circle Trader (ICT) - บริหารโดย **AURA-QUANT**")

if not supabase:
    st.info(
        "ℹ️ ยังไม่ได้ตั้งค่า Supabase — Dashboard กำลังทำงานในโหมด Offline\n\n"
        "บอทยังเทรดได้ปกติ แต่ไม่มีการบันทึกประวัติออเดอร์ลงฐานข้อมูล\n\n"
        "**เพิ่ม Supabase:** ใส่ `SUPABASE_URL` และ `SUPABASE_KEY` ลงในไฟล์ `.env` แล้วรีสตาร์ท Dashboard ครับ"
    )
    st.markdown("### 📋 วิธีตั้งค่า Supabase")
    st.code("""
# เพิ่มบรรทัดเหล่านี้ในไฟล์ .env
SUPABASE_URL=https://xxxxxxxxxxxx.supabase.co
SUPABASE_KEY=your_supabase_anon_key
    """, language="bash")
    st.stop()

@st.cache_data(ttl=30)
def load_data():
    try:
        response = supabase.table("trades").select("*").order("entry_time", desc=False).execute()
        df = pd.DataFrame(response.data)
        if not df.empty:
            df['entry_time'] = pd.to_datetime(df['entry_time'])
            if 'close_time' in df.columns:
                df['close_time'] = pd.to_datetime(df['close_time'])
        return df, None
    except Exception as e:
        err_msg = str(e)
        return pd.DataFrame(), err_msg

df, err_msg = load_data()

if err_msg and "PGRST205" in err_msg:
    st.warning("🛠️ **ยังไม่ได้สร้างตาราง 'trades' ในฐานข้อมูล Supabase**")
    st.info("กรุณาคัดลอก SQL ด้านล่างนี้ไปวางใน **Supabase -> SQL Editor** แล้วกด Run เพื่อเริ่มต้นใช้งานแอปพลิเคชัน:")
    st.code("""
CREATE TABLE IF NOT EXISTS trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL UNIQUE,
  symbol TEXT NOT NULL,
  type TEXT NOT NULL,
  entry_time TIMESTAMP WITH TIME ZONE NOT NULL,
  close_time TIMESTAMP WITH TIME ZONE,
  entry_price DOUBLE PRECISION NOT NULL,
  sl DOUBLE PRECISION NOT NULL,
  tp DOUBLE PRECISION NOT NULL,
  lot_size DOUBLE PRECISION NOT NULL,
  fvg_size DOUBLE PRECISION,
  session TEXT,
  profit_loss DOUBLE PRECISION DEFAULT 0.0,
  status TEXT NOT NULL DEFAULT 'OPEN'
);

CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_entry_time ON trades(entry_time);
""", language="sql")
elif df.empty:
    st.info("ℹ️ ยังไม่มีข้อมูลประวัติการเทรดในฐานข้อมูล (บอทพร้อมทำงานและจะบันทึกออเดอร์เมื่อเกิดสัญญาณเข้าเทรด)")
else:
    # คำนวณสถิติ
    total_trades = len(df)
    closed_trades = df[df['status'] != 'OPEN']
    wins = len(closed_trades[closed_trades['status'] == 'WIN'])
    losses = len(closed_trades[closed_trades['status'] == 'LOSS'])
    win_rate = (wins / len(closed_trades) * 100) if len(closed_trades) > 0 else 0
    total_pl = closed_trades['profit_loss'].sum() if not closed_trades.empty else 0
    
    # แสดง KPI
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Trades", total_trades)
    col2.metric("Win Rate", f"{win_rate:.2f}%")
    col3.metric("Total P/L (USD)", f"${total_pl:.2f}")
    col4.metric("Active Open Trades", len(df[df['status'] == 'OPEN']))

    st.markdown("---")
    
    col_chart, col_stats = st.columns([2, 1])
    
    with col_chart:
        st.subheader("Equity Curve (Cumulative P/L)")
        if not closed_trades.empty:
            closed_trades = closed_trades.sort_values(by='close_time')
            closed_trades['cum_pl'] = closed_trades['profit_loss'].cumsum()
            fig = px.line(closed_trades, x='close_time', y='cum_pl', title='Cumulative Profit/Loss over time')
            st.plotly_chart(fig, use_container_width=True)
            
    with col_stats:
        st.subheader("Performance by Session")
        if not closed_trades.empty and 'session' in closed_trades.columns:
            session_stats = closed_trades.groupby('session').agg(
                Trades=('ticket_id', 'count'),
                Win_Rate=('status', lambda x: (x == 'WIN').mean() * 100),
                Total_PL=('profit_loss', 'sum')
            ).reset_index()
            session_stats['Win_Rate'] = session_stats['Win_Rate'].round(2)
            st.dataframe(session_stats, use_container_width=True)

    st.markdown("---")
    st.subheader("Trade History")
    st.dataframe(df.sort_values(by='entry_time', ascending=False), use_container_width=True)
