-- สร้างตาราง 'trades' สำหรับเก็บประวัติการเทรดของบอท
CREATE TABLE trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL UNIQUE,
  symbol TEXT NOT NULL,
  type TEXT NOT NULL,
  entry_time TIMESTAMP WITH TIME ZONE NOT NULL,
  close_time TIMESTAMP WITH TIME ZONE,
  entry_price DOUBLE PRECISION NOT NULL,
  sl DOUBLE PRECISION NOT NULL,
  tp DOUBLE PRECISION NOT NULL,
  lot_size DOUBLE PRECISION NOT NULL,
  fvg_size DOUBLE PRECISION,
  session TEXT,
  profit_loss DOUBLE PRECISION DEFAULT 0.0,
  status TEXT NOT NULL DEFAULT 'OPEN'
);

-- สร้าง Index เพื่อให้ดึงข้อมูลได้เร็วขึ้นเมื่อใช้ AI หรือ Dashboard
CREATE INDEX idx_trades_status ON trades(status);
CREATE INDEX idx_trades_entry_time ON trades(entry_time);
